"""batch.py — RaC PyMOL batch pipeline.

Each run produces a timestamped subdir under .rendering/random/<YYYYMMDD_HHMMSS>/
containing applied PNGs for the reference plus each subject, and a slides.html
generated by the embedded Vis submodule.

Structures are sourced from tests/data first, then downloaded from RCSB and
cached under .rendering/_cif_cache/.

Run from rac_pymol/:
    python pymol-workshop/batch.py <ref_pdb_id>
"""

import base64
import datetime as dt
import http.server
import json
import math
import os
import random
import shutil
import sys
import threading
import urllib.request
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).parent.parent
sys.path.insert(0, str(ROOT))

import pymol  # noqa: E402
pymol.finish_launching(["pymol", "-cq"])
from pymol import cmd  # noqa: E402

from pymol_backend.adapter import PyMOLController  # noqa: E402
from pymol_backend.driver import apply_scene  # noqa: E402

# ── config ─────────────────────────────────────────────────────────────────

FETCH_TIMEOUT = 15
RENDER_ROOT   = ROOT / ".rendering"
RANDOM_DIR    = RENDER_ROOT / "random"
CIF_CACHE     = RENDER_ROOT / "_cif_cache"
RCSB_URL      = "https://files.rcsb.org/download/{}.cif"
RCSB_SEARCH   = "https://search.rcsb.org/rcsbsearch/v2/query"

# Category → RCSB entity-type / keyword used in full-text search
PDB_CATEGORIES = {
    "enzyme":        "enzyme catalytic",
    "antibody":      "immunoglobulin antibody",
    "membrane":      "membrane protein",
    "nucleic_acid":  "DNA RNA nucleic acid",
    "virus":         "viral capsid virus",
    "kinase":        "protein kinase",
    "receptor":      "receptor ligand binding",
}

# Pick one category per run (can be overridden via env var BATCH_CATEGORY)
_env_cat = os.environ.get("BATCH_CATEGORY", "")
SELECTED_CATEGORY = _env_cat if _env_cat in PDB_CATEGORIES else random.choice(list(PDB_CATEGORIES.keys()))
N_SUBJECTS = int(os.environ.get("BATCH_N_SUBJECTS", "5"))

RANDOM_DIR.mkdir(parents=True, exist_ok=True)
CIF_CACHE.mkdir(exist_ok=True)

STATUS_PORT = 8091
STATUS_FILE = RANDOM_DIR / "status.json"


def write_status(state: str, step: str, msg: str, **extra) -> None:
    """Write .rendering/random/status.json so the local UI can poll progress."""
    payload = {"state": state, "step": step, "msg": msg, **extra}
    STATUS_FILE.write_text(json.dumps(payload))


def start_local_server() -> None:
    """Start a daemon HTTP server on STATUS_PORT serving the repo ROOT.
    Silently skips if the port is already bound (e.g. second run).
    Serves everything under ROOT so index.html and .rendering/random/ are
    reachable at the same origin: http://127.0.0.1:8091/
    """
    import socketserver

    class _Handler(http.server.SimpleHTTPRequestHandler):
        def __init__(self, *a, **kw):
            super().__init__(*a, directory=str(ROOT), **kw)

        def log_message(self, *_):  # silence access log
            pass

    def _serve():
        try:
            with socketserver.TCPServer(("127.0.0.1", STATUS_PORT), _Handler) as httpd:
                httpd.serve_forever()
        except OSError:
            pass  # port already in use — that's fine

    threading.Thread(target=_serve, daemon=True).start()
    print(f"[batch] local server → http://127.0.0.1:{STATUS_PORT}/  (serving repo root)")


# ── Vis — slide deck submodule ───────────────────────────────────────────────

class Vis:
    """Self-contained slide-deck builder (formerly slides.py)."""

    BG   = "#1c0524"
    SURF = "#270833"
    FG   = "#ffffff"
    HI   = "#AB0061"
    HI2  = "#8b0a5e"
    GRID = "#4a1a6b"
    MUTE = "#b078a8"

    _STATE_DEFAULT = ROOT / "tests" / "data" / "visual_system_state.json"

    _GS_CATEGORIES = [
        ("Lighting",     ["light", "reflect", "specular", "ambient", "direct", "shininess", "ray_shadow"]),
        ("Rendering",    ["ray", "render", "antialias", "depth_cue", "fog", "ortho", "opaque", "power"]),
        ("Display",      ["bg", "valence", "stick", "sphere", "cartoon", "ribbon", "label", "surface",
                          "mesh", "dot", "nonbonded", "line", "transparency", "cgo", "overlay"]),
        ("Camera",       ["clip", "fov", "field_of_view", "zoom", "view", "roving"]),
        ("Performance",  ["cache", "async", "max_threads", "hash", "texture", "defer", "swap"]),
        ("Picking",      ["pick", "mouse", "select", "button", "sel_counter"]),
        ("Motifs",       ["solvent", "ss_strand", "phi", "psi", "strand", "helix", "turn"]),
        ("Sculpting",    ["sculpt", "sculpting"]),
        ("IO/PDB",       ["pdb", "normalize", "grd", "dsn6", "insertions", "retain_ids",
                          "no_end_record", "byte"]),
        ("UI",           ["internal_prompt", "internal_gui", "internal_feedback", "movie_loop",
                          "movie", "prompt", "gui", "feedback"]),
    ]
    _CAT_COLORS = {
        "Lighting":     "#ff5ecb",
        "Rendering":    "#AB0061",
        "Display":      "#e040a0",
        "Camera":       "#ff5ecb",
        "Performance":  "#8b0a5e",
        "Picking":      "#e040a0",
        "Motifs":       "#ff5ecb",
        "Sculpting":    "#8b0a5e",
        "IO/PDB":       "#8b0a5e",
        "UI":           "#e040a0",
    }

    # ── static helpers ────────────────────────────────────────────────────

    @staticmethod
    def _img_b64(path: Path) -> str:
        with open(path, "rb") as f:
            return "data:image/png;base64," + base64.b64encode(f.read()).decode()

    @classmethod
    def _resolve_state(cls, output_dir: Path | None = None) -> dict:
        candidates = []
        if output_dir:
            candidates.append(Path(output_dir) / "visual_system_state.json")
        candidates.append(cls._STATE_DEFAULT)
        for p in candidates:
            if p.exists():
                return json.loads(p.read_text())
        raise FileNotFoundError(f"visual_system_state.json not found. Tried: {candidates}")

    @classmethod
    def _gs_category(cls, key: str) -> str:
        kl = key.lower()
        for cat, keywords in cls._GS_CATEGORIES:
            if any(kw in kl for kw in keywords):
                return cat
        return "Other"

    # ── slide constructors ────────────────────────────────────────────────

    @classmethod
    def slide_image(cls, title: str, img_path: Path):
        src = cls._img_b64(img_path)
        html = (
            f'<div class="img-slide-title">{title}</div>'
            f'<div class="img-row" style="grid-template-columns:1fr;">'
            f'<div class="img-col"><img src="{src}" alt="{title}"></div></div>'
        )
        return ("html", title, html)

    @classmethod
    def slide_compare(cls, title: str, paths: dict,
                      col_weights: list[int] | None = None,
                      subtitle: str | None = None):
        ncols = len(paths)
        grid_cols = (
            " ".join(f"{w}fr" for w in col_weights)
            if col_weights and len(col_weights) == ncols
            else " ".join("1fr" for _ in range(ncols))
        )
        subtitle_html = (
            f'\n<div class="img-slide-subtitle"><a href="{subtitle}" target="_blank">Crystal ID</a></div>'
            if subtitle
            else '\n<div class="img-slide-subtitle">Crystal ID</div>'
        )
        cols_html = ""
        for label, path in paths.items():
            src = cls._img_b64(path)
            is_applied = label.lower() == "applied"
            col_cls = "img-col img-col--applied" if is_applied else "img-col"
            badge = '\n    <div class="db-badge">&#x2713;&nbsp;WRITTEN TO SCNgraphy</div>' if is_applied else ""
            cols_html += (
                f'\n  <div class="{col_cls}">'
                f'\n    <div class="col-label" title="{label}">{label}</div>'
                f'\n    <div class="img-wrap"><img src="{src}" alt="{label}"></div>{badge}'
                f'\n  </div>'
            )
        html = (
            f'\n<div class="img-slide-title">{title}</div>{subtitle_html}'
            f'\n<div class="img-row" style="grid-template-columns:{grid_cols};">{cols_html}\n</div>'
        )
        return ("html", title, html)

    @classmethod
    def slide_repr_heatmap(cls, state: dict):
        import plotly.graph_objects as go
        objects = state["objects"]
        repr_keys = ["cartoon", "sticks", "spheres", "surface", "mesh", "dots", "lines", "nonbonded"]
        obj_names = list(objects.keys())
        z = [
            [1 if objects[obj].get("representations", {}).get(r, False) else 0 for r in repr_keys]
            for obj in obj_names
        ]
        fig = go.Figure(go.Heatmap(
            z=z, x=repr_keys, y=obj_names,
            colorscale=[[0, cls.BG], [1, cls.HI]],
            showscale=False, xgap=3, ygap=3,
            text=[["ON" if v else "" for v in row] for row in z],
            texttemplate="%{text}",
            textfont=dict(size=14, color=cls.FG),
            hovertemplate="<b>%{y}</b> · %{x}: %{text}<extra></extra>",
        ))
        fig.update_layout(
            title=dict(text="Object · Representation Matrix", font=dict(size=20, color=cls.FG),
                       xref="paper", x=0, xanchor="left",
                       yref="paper", y=1.0, yanchor="bottom", pad=dict(b=12)),
            xaxis=dict(tickfont=dict(size=13, color=cls.FG), side="bottom",
                       gridcolor=cls.HI2, showgrid=True, zeroline=False, tickangle=-30),
            yaxis=dict(tickfont=dict(size=12, color=cls.FG), autorange="reversed",
                       gridcolor=cls.HI2, showgrid=True, zeroline=False, ticklabelstandoff=8),
            paper_bgcolor=cls.BG, plot_bgcolor=cls.SURF,
            margin=dict(l=220, r=30, t=36, b=60),
        )
        return ("plotly", "Repr Matrix", fig)

    @classmethod
    def slide_global_settings(cls, state: dict):
        import plotly.graph_objects as go

        def slog(v):
            return math.copysign(math.log1p(abs(v)), v)

        gs = state["global_settings"]

        _HIDDEN_CATS = {"Other", "UI", "IO/PDB"}

        # Collect numeric rows and classify (skip hidden categories)
        raw_rows: list[dict] = []
        for k, v in gs.items():
            try:
                cat = cls._gs_category(k)
                if cat in _HIDDEN_CATS:
                    continue
                raw_rows.append({"key": k, "val": float(v), "cat": cat})
            except (ValueError, TypeError):
                pass

        # Group by category → keep top 3 by abs(val) → clamp to [-100, 100]
        by_cat: dict = defaultdict(list)
        for r in raw_rows:
            by_cat[r["cat"]].append(r)

        filtered: list[dict] = []
        for cat in sorted(by_cat):
            top3 = sorted(by_cat[cat], key=lambda r: -abs(r["val"]))[:3]
            for r in top3:
                clamped = max(-100.0, min(100.0, r["val"]))
                filtered.append({"key": r["key"], "val": r["val"], "clamped": clamped, "cat": cat})

        # Assign y positions (gap between categories)
        y_pos: list[float] = []
        y_labels: list[str] = []
        y, prev_cat = 0.0, None
        for r in filtered:
            if r["cat"] != prev_cat:
                if prev_cat is not None:
                    y += 2.0
                prev_cat = r["cat"]
            else:
                y += 1.0
            y_pos.append(y)
            y_labels.append(r["key"])

        # Group by cat for plotting
        cat_items: dict = defaultdict(list)
        cat_y: dict = defaultdict(list)
        for i, r in enumerate(filtered):
            cat_items[r["cat"]].append((i, r))
            cat_y[r["cat"]].append(y_pos[i])

        fig = go.Figure()

        # Alternating band backgrounds
        for band_i, (cat, ys) in enumerate(cat_y.items()):
            if band_i % 2 == 0:
                fig.add_hrect(y0=min(ys) - 0.5, y1=max(ys) + 0.5,
                               fillcolor="rgba(255,255,255,0.03)", line_width=0, layer="below")

        fig.add_vline(x=0, line=dict(color=cls.MUTE, dash="dot", width=1))

        seen: set = set()
        for cat, items in cat_items.items():
            color = cls._CAT_COLORS.get(cat, cls.GRID)
            show_legend = cat not in seen
            seen.add(cat)
            for j, (i, r) in enumerate(items):
                was_clamped = abs(r["val"]) > 100.0
                fig.add_trace(go.Scatter(
                    x=[slog(r["clamped"])], y=[y_pos[i]], mode="markers",
                    marker=dict(
                        size=13,
                        color=color,
                        opacity=0.85,
                        symbol="triangle-right" if was_clamped else "circle",
                        line=dict(color=cls.BG, width=1),
                    ),
                    name=cat, legendgroup=cat, showlegend=show_legend and j == 0,
                    text=[r["key"]],
                    customdata=[[cat, r["val"], was_clamped]],
                    hovertemplate=(
                        "<b>%{text}</b><br>%{customdata[0]}<br>"
                        "value: %{customdata[1]:.4g}"
                        "%{customdata[2]:<br><i>clamped to ±100</i>}<extra></extra>"
                    ),
                ))

        # Category labels on the right
        for cat, ys in cat_y.items():
            mid = (min(ys) + max(ys)) / 2
            fig.add_annotation(
                x=1.02, y=mid, xref="paper", yref="y",
                text=f"<b>{cat}</b>", showarrow=False,
                font=dict(size=12, color=cls._CAT_COLORS.get(cat, cls.GRID)),
                xanchor="left",
            )

        tick_raw = [-100, -10, -1, 0, 1, 10, 100]
        fig.update_layout(
            title=dict(
                text="Render Parameters  ·  by Category",
                font=dict(size=20, color=cls.FG),
                xref="paper", x=0, xanchor="left",
                yref="paper", y=1.0, yanchor="bottom", pad=dict(b=12),
            ),
            xaxis=dict(
                title=dict(text="SignedLog", font=dict(size=13, color=cls.MUTE)),
                tickvals=[slog(v) for v in tick_raw],
                ticktext=[str(v) for v in tick_raw],
                tickfont=dict(size=12, color=cls.FG),
                gridcolor=cls.GRID, zeroline=False,
            ),
            yaxis=dict(
                tickvals=y_pos, ticktext=y_labels,
                tickfont=dict(size=11, color=cls.FG),
                gridcolor=cls.GRID, showgrid=False,
            ),
            showlegend=False,
            paper_bgcolor=cls.BG, plot_bgcolor=cls.SURF,
            margin=dict(l=220, r=120, t=36, b=50),
        )
        return ("plotly", "Global Settings", fig)

    @classmethod
    def slide_view_matrix(cls, state: dict):
        import plotly.graph_objects as go
        vm = state["view_matrix"]
        y_labels = [
            "rot X→X","rot X→Y","rot X→Z",
            "rot Y→X","rot Y→Y","rot Y→Z",
            "rot Z→X","rot Z→Y","rot Z→Z",
            "shift X","shift Y","shift Z",
            "origin X","origin Y","origin Z",
            "clip near","clip far","field of view",
        ]
        hover_desc = [
            "Rotation row 0, col 0","Rotation row 0, col 1","Rotation row 0, col 2",
            "Rotation row 1, col 0","Rotation row 1, col 1","Rotation row 1, col 2",
            "Rotation row 2, col 0","Rotation row 2, col 1","Rotation row 2, col 2",
            "Camera translation X","Camera translation Y","Camera translation Z",
            "Scene origin X","Scene origin Y","Scene origin Z",
            "Near clipping plane","Far clipping plane","Field of view (degrees)",
        ]
        group_colors = [cls.HI]*9 + ["#ff5ecb"]*3 + ["#e040a0"]*3 + [cls.HI2]*3
        group_names  = (["Rotation matrix"]*9 + ["Translation (pan/zoom)"]*3
                        + ["Scene origin"]*3 + ["Clip / FoV"]*3)
        fig = go.Figure(go.Bar(
            x=vm, y=y_labels, orientation="h",
            marker=dict(color=group_colors, line=dict(color=cls.BG, width=0.5)),
            text=[f"{v:.3f}" for v in vm], textposition="outside",
            textfont=dict(size=12, color=cls.FG),
            customdata=list(zip(hover_desc, group_names)),
            hovertemplate="<b>%{y}</b><br>%{customdata[0]}<br><i>%{customdata[1]}</i><br>value: %{x:.4f}<extra></extra>",
        ))
        fig.add_vline(x=0, line=dict(color=cls.GRID, dash="dot", width=1))
        for sep in [8.5, 11.5, 14.5]:
            fig.add_hline(y=sep, line=dict(color=cls.GRID, width=1.0, dash="dot"))
        fig.update_layout(
            title=dict(text="Camera Grid  ·  18 params.", font=dict(size=22, color=cls.FG),
                       xref="paper", x=0, xanchor="left",
                       yref="paper", y=1.0, yanchor="bottom", pad=dict(b=12)),
            xaxis=dict(title=dict(text="offset", font=dict(size=14, color=cls.FG)),
                       tickfont=dict(size=13, color=cls.FG),
                       gridcolor=cls.GRID, zeroline=False),
            yaxis=dict(tickfont=dict(size=13, color=cls.FG), autorange="reversed",
                       gridcolor=cls.GRID),
            paper_bgcolor=cls.BG, plot_bgcolor=cls.SURF,
            margin=dict(l=140, r=60, t=36, b=40), bargap=0.25,
        )
        return ("plotly", "View Matrix", fig)

    # ── image slide assembly ──────────────────────────────────────────────

    @classmethod
    def _find_png(cls, img_dir: Path, stem: str) -> Path | None:
        for variant in (stem, stem.upper(), stem.lower()):
            p = img_dir / f"{variant}_applied.png"
            if p.exists():
                return p
        return None

    @classmethod
    def _image_slides(cls, reference: str, subjects: list[str], img_dir: Path) -> list:
        src_file = img_dir / ".source.json"
        rcsb_urls: dict = {}
        if src_file.exists():
            try:
                rcsb_urls = json.loads(src_file.read_text()).get("rcsb_urls", {})
            except Exception:
                pass

        slides = []
        ref_panels = {}
        for phase in ("loaded", "applied"):
            for variant in (reference, reference.upper(), reference.lower()):
                p = img_dir / f"{variant}_{phase}.png"
                if p.exists():
                    ref_panels[phase] = p
                    break
        if ref_panels:
            weights = [1] + [2] * (len(ref_panels) - 1)
            slides.append(cls.slide_compare(
                reference.upper(), ref_panels,
                col_weights=weights,
                subtitle=rcsb_urls.get(reference.upper()),
            ))

        ref_col_img = None
        for phase in ("staged", "applied"):
            for variant in (reference, reference.upper(), reference.lower()):
                p = img_dir / f"{variant}_{phase}.png"
                if p.exists():
                    ref_col_img = p
                    break
            if ref_col_img:
                break

        for mol in subjects:
            panels = {}
            if ref_col_img:
                panels["ORIGINAL SCENE"] = ref_col_img
            p = cls._find_png(img_dir, mol)
            if p:
                panels[f"{mol.upper()}  ·  RCSB PDB"] = p
            if panels:
                slides.append(cls.slide_compare(
                    mol.upper(), panels,
                    subtitle=rcsb_urls.get(mol.upper()),
                ))
        return slides

    # ── HTML shell ────────────────────────────────────────────────────────

    @classmethod
    def _css(cls) -> str:
        B, S, F, H, H2, M = cls.BG, cls.SURF, cls.FG, cls.HI, cls.HI2, cls.MUTE
        return f"""<style>
  *, *::before, *::after {{ box-sizing: border-box; margin: 0; padding: 0; }}
  html, body {{ height: 100vh; width: 100vw; overflow: hidden;
               background: {B}; color: {F}; font-family: sans-serif; }}
  #shell {{ display: flex; flex-direction: column; height: 100vh; width: 100vw;
           background: {B}; overflow: hidden; }}
  #source-banner {{ height: 36px; flex-shrink: 0; display: flex; align-items: center;
                   justify-content: center; gap: 10px; background: {B};
                   border-bottom: 2px solid {H}; padding: 0 20px; font-size: 12px; }}
  .src-label {{ color: {M}; text-transform: uppercase; font-size: 10px;
               font-weight: 700; letter-spacing: 0.1em; }}
  .src-file  {{ color: {F}; font-family: monospace; font-size: 12px;
               background: {S}; padding: 2px 8px; border-radius: 4px;
               border: 1px solid {H}; }}
  #nav {{ height: 40px; flex-shrink: 0; display: flex; align-items: center;
         justify-content: center; gap: 12px; background: {B}; }}
  #slide-counter {{ font-size: 12px; color: {M}; font-variant-numeric: tabular-nums;
                   min-width: 48px; text-align: center; letter-spacing: 0.04em; }}
  button {{ background: {S}; color: {F}; border: 1px solid {H}; padding: 5px 18px;
           border-radius: 5px; cursor: pointer; font-size: 13px; font-weight: 600; }}
  button:hover {{ background: {H}; }}
  #slides-wrap {{ flex: 1 1 0; min-height: 0; position: relative; background: {B}; }}
  .slide {{ display: none; position: absolute; inset: 0; overflow: hidden;
           flex-direction: column; padding: 6px 16px 8px; background: {B}; }}
  .slide.on {{ display: flex; }}
  .img-slide-title {{ font-size: 18px; font-weight: 700; color: {F};
                     text-align: right; flex-shrink: 0; margin-bottom: 2px; }}
  .img-slide-subtitle {{ font-size: 10px; font-weight: 700; text-transform: uppercase;
                        letter-spacing: 0.1em; color: {M}; text-align: right;
                        flex-shrink: 0; margin-bottom: 4px; }}
  .img-slide-subtitle a {{ color: {M}; text-decoration: none; }}
  .img-slide-subtitle a:hover {{ color: {F}; text-decoration: underline; }}
  .img-row {{ flex: 1 1 0; min-height: 0; display: grid; gap: 10px; align-items: center; }}
  .img-col {{ min-width: 0; min-height: 0; display: flex; flex-direction: column;
             align-items: center; }}
  .col-label {{ font-size: 11px; text-transform: uppercase; letter-spacing: 0.08em;
               color: {M}; flex-shrink: 0; margin-bottom: 4px;
               overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }}
  .img-col img {{ width: 100%; height: auto; max-height: 74vh; object-fit: contain;
                 border-radius: 5px; border: 1px solid {H}; display: block; }}
  .img-wrap {{ position: relative; width: 100%; }}
  .img-col--applied {{ outline: 3px solid {H}; outline-offset: 3px; border-radius: 6px;
                      box-shadow: 0 0 18px 4px {H}55, 0 0 40px 8px {H2}; }}
  .img-col--applied .img-wrap img {{ border: 2px solid {H} !important; }}
  .db-badge {{ display: inline-block; margin-top: 6px; font-size: 9px; font-weight: 700;
              text-transform: uppercase; letter-spacing: 0.10em; color: {H};
              background: rgba(28,5,36,0.82); padding: 2px 8px; border-radius: 3px;
              border: 1px solid {H}; }}
  .plot-wrap {{ flex: 1 1 0; min-height: 0; display: flex; align-items: center;
               justify-content: flex-start; }}
  .plotly-graph-div {{ flex: 1 1 0 !important; min-height: 0 !important;
                      width: 92% !important; max-width: 92% !important;
                      margin: 0 !important; display: block !important; }}
</style>"""

    # ── main entry point ──────────────────────────────────────────────────

    @classmethod
    def build_deck(cls, molecules: list[str], output_dir: Path) -> Path:
        """Build slide deck HTML from rendered PNGs in *output_dir*."""
        import plotly.offline as poff
        img_dir = Path(output_dir)
        state = cls._resolve_state(img_dir)

        reference = molecules[0]
        subjects  = molecules[1:]

        slides = cls._image_slides(reference, subjects, img_dir)
        slides += [
            cls.slide_repr_heatmap(state),
            cls.slide_global_settings(state),
            cls.slide_view_matrix(state),
        ]
        total = len(slides)

        divs_html = ""
        for i, (kind, title, content) in enumerate(slides):
            cls_ = "slide on" if i == 0 else "slide"
            inner = (
                content if kind == "html"
                else f'<div class="plot-wrap">{content.to_html(full_html=False, include_plotlyjs=False)}</div>'
            )
            divs_html += f'<div class="{cls_}" id="slide-{i}">{inner}</div>\n'

        titles_json = json.dumps([title for _, title, _ in slides])
        src_file = img_dir / ".source.json"
        source_banner = ""
        if src_file.exists():
            src = json.loads(src_file.read_text())
            tpath = src.get("template_path", "")
            source_banner = (
                '<div id="source-banner">'
                '<span class="src-label">generated by</span>'
                f'<span class="src-file">{tpath}</span>'
                '</div>'
            )

        nav = (
            '<div id="nav">'
            '<button onclick="go(-1)">&#8592; Prev</button>'
            '<span id="slide-counter"></span>'
            '<button onclick="go(+1)">Next &#8594;</button>'
            '</div>'
        )
        js = f"""<script>
var cur=0,total={total},titles={titles_json};
function updateCounter(){{document.getElementById('slide-counter').textContent=(cur+1)+' / '+total;}}
function go(d){{document.getElementById('slide-'+cur).classList.remove('on');cur=(cur+d+total)%total;document.getElementById('slide-'+cur).classList.add('on');updateCounter();}}
document.addEventListener('keydown',function(e){{if(e.key==='ArrowRight'||e.key==='ArrowDown')go(+1);if(e.key==='ArrowLeft'||e.key==='ArrowUp')go(-1);}});
updateCounter();
</script>"""

        html = (
            f'<!DOCTYPE html><html><head><meta charset="utf-8">'
            f'<title>RAC PyMOL – Slide Deck</title>'
            f'<script>{poff.get_plotlyjs()}</script>'
            f'{cls._css()}'
            f'</head><body><div id="shell">{source_banner}{nav}'
            f'<div id="slides-wrap">{divs_html}</div></div>{js}</body></html>'
        )
        out = img_dir / "slides.html"
        out.write_text(html)
        print(f"[slides] saved → {out}  ({total} slides)")
        return out


# ── helpers ─────────────────────────────────────────────────────────────────

def query_rcsb_by_category(category: str, n: int = 10) -> list[str]:
    """Return up to *n* PDB IDs matching *category* via RCSB full-text search."""
    keyword = PDB_CATEGORIES.get(category, category)
    payload = json.dumps({
        "query": {
            "type": "terminal",
            "service": "full_text",
            "parameters": {"value": keyword},
        },
        "return_type": "entry",
        "request_options": {
            "paginate": {"start": 0, "rows": n * 3},
            "sort": [{"sort_by": "score", "direction": "desc"}],
        },
    }).encode()
    req = urllib.request.Request(
        RCSB_SEARCH,
        data=payload,
        headers={"Content-Type": "application/json"},
        method="POST",
    )
    try:
        with urllib.request.urlopen(req, timeout=FETCH_TIMEOUT) as resp:
            hits = json.loads(resp.read())
        ids = [h["identifier"] for h in hits.get("result_set", [])]
        random.shuffle(ids)
        return ids[:n]
    except Exception as exc:
        print(f"  [WARN]   RCSB search failed for '{category}': {exc}")
        return []


def locate_cif(pdb_id: str, cif_dir: Path | None = None) -> Path | None:
    """Return CIF path: tests/data first, then *cif_dir* (run-local cache),
    then global CIF_CACHE, then download and store in both."""
    local = ROOT / "tests" / "data" / f"{pdb_id.lower()}.cif"
    if local.exists():
        return local

    # run-local timestamped cache dir (preferred store)
    run_cached = (cif_dir / f"{pdb_id.lower()}.cif") if cif_dir else None
    if run_cached and run_cached.exists():
        return run_cached

    global_cached = CIF_CACHE / f"{pdb_id.lower()}.cif"
    if global_cached.exists():
        # copy into run dir as well
        if run_cached:
            run_cached.write_bytes(global_cached.read_bytes())
        return run_cached or global_cached

    url = RCSB_URL.format(pdb_id.upper())
    try:
        print(f"  [fetch]  {url}")
        with urllib.request.urlopen(url, timeout=FETCH_TIMEOUT) as resp:
            data = resp.read()
        global_cached.write_bytes(data)
        if run_cached:
            run_cached.write_bytes(data)
        return run_cached or global_cached
    except Exception as exc:
        print(f"  [WARN]   fetch failed for {pdb_id}: {exc}")
        return None


def write_run_meta(path: Path, meta: dict) -> None:
    """Append / overwrite the run metadata JSON at *path*."""
    path.write_text(json.dumps(meta, indent=2))
    print(f"  [meta]   {path.name} written")


RCSB_ENTRY_URL = "https://www.rcsb.org/structure/{}"


def rcsb_entry_url(pdb_id: str) -> str:
    """Return the canonical RCSB entry URL for *pdb_id* (hardcoded template)."""
    return RCSB_ENTRY_URL.format(pdb_id.upper())


def _build_visual_state(ctrl: "PyMOLController", scene_id: int) -> dict:
    """Build visual_system_state.json content from DB scene data.

    Reads scene meta (global_settings, view_matrix) and scene objects
    (per-BT native representations) from the DB so the Vis slide deck
    reflects the actual scene rather than the static test-data fallback.
    """
    scene    = ctrl.load_scene(scene_id)
    meta     = json.loads(scene["meta"])
    obj_recs = ctrl.load_scene_objects(scene_id)

    objects: dict = {}
    for rec in obj_recs:
        bt      = rec["name"]
        payload = json.loads(rec["payload"])
        bucket  = (payload.get("objects") or {}).get(bt) or {}
        native  = bucket.get("native") or {}

        if bt == "chains":
            # Each sub-key is a chain letter → its own entry in the state objects map
            for chain_letter, chain_bucket in bucket.items():
                if isinstance(chain_bucket, dict):
                    chain_native = chain_bucket.get("native") or {}
                    objects[f"chain_{chain_letter}"] = {
                        "representations": chain_native.get("representations") or {}
                    }
        else:
            objects[bt] = {"representations": native.get("representations") or {}}

    return {
        "objects":         objects,
        "view_matrix":     json.loads(scene["view"]),
        "global_settings": meta.get("global_settings") or {},
    }


# ── main ─────────────────────────────────────────────────────────────────────

def main(ref: str) -> None:
    """Batch pipeline.

    *ref* — the reference PDB ID passed via sys.argv (same one enzyme.py
    styled and stored to DB).  Candidates are queried from RCSB and rendered
    with the same scene from DB.
    """
    _ui = os.environ.get("RAC_LOCAL_UI") == "1"  # set by local.sh
    if _ui:
        start_local_server()

    ctrl = PyMOLController()
    print(f"[batch] DB: {ctrl._db.path}")

    # Timestamped output dir — use pre-minted tag from caller (local.sh) if
    # available, so the UI knows the dir before the run starts.  Falls back to
    # generating its own tag (e.g. on GitHub Actions).
    run_tag = os.environ.get("BATCH_RUN_TAG") or dt.datetime.now().strftime("%Y%m%d_%H%M%S")
    run_dir = RANDOM_DIR / run_tag
    run_dir.mkdir(parents=True, exist_ok=True)
    print(f"[batch] run dir: {run_dir}")

    # ── scene from DB — prefer scene whose name contains the ref PDB ID ──
    all_scenes = ctrl.list_scenes()
    if not all_scenes:
        print("[batch] ERROR: no scenes in DB — run enzyme.py / simple.py first")
        cmd.quit()
        return
    # Pick the scene whose name contains the ref PDB ID (case-insensitive).
    # Fall back to the most recent scene if none match.
    matched = [s for s in all_scenes if ref.lower() in s["name"].lower()]
    scene_row  = matched[-1] if matched else all_scenes[-1]
    scene_id   = scene_row["id"]
    scene_name = scene_row["name"]
    print(f"  [db] scene '{scene_name}' id={scene_id}")

    _source_meta = {
        "template": Path(__file__).name,
        "template_path": str(Path(__file__).relative_to(ROOT.parent)),
        "generated_at": dt.datetime.now().isoformat(timespec="seconds"),
        "category": SELECTED_CATEGORY,
        "scene": scene_name,
        "rcsb_urls": {ref.upper(): rcsb_entry_url(ref)},
    }
    source_path = run_dir / ".source.json"
    source_path.write_text(json.dumps(_source_meta, indent=2))

    # ── Phase A: reference — DB replay ───────────────────────────────────
    print(f"\n[batch] REFERENCE ── {ref}")
    ref_cif = locate_cif(ref, run_dir)
    if ref_cif is None:
        print(f"[batch] ERROR: cannot locate reference CIF {ref}")
        cmd.quit()
        return
    cmd.reinitialize()
    cmd.load(str(ref_cif), ref)
    cmd.viewport(800, 600)
    apply_scene(scene_id=scene_id)
    cmd.png(str(run_dir / f"{ref}_applied.png"), width=800, height=600, ray=1)
    print(f"  ✓ {ref}_applied.png")

    # Copy loaded/staged PNGs from base .rendering dir so slide 1 shows all phases.
    for phase in ("loaded", "staged"):
        for variant in (ref, ref.upper(), ref.lower()):
            src = RENDER_ROOT / f"{variant}_{phase}.png"
            if src.exists():
                shutil.copy2(src, run_dir / f"{ref}_{phase}.png")
                print(f"  ✓ {ref}_{phase}.png  (copied from .rendering/)")
                break

    # ── Phase B: candidates — RCSB query, DB replay ───────────────────────
    print(f"\n[batch] querying RCSB category '{SELECTED_CATEGORY}' …")
    candidate_ids = query_rcsb_by_category(SELECTED_CATEGORY, n=N_SUBJECTS)
    if not candidate_ids:
        print("[batch] WARN: no results from RCSB, falling back to hardcoded list")
        candidate_ids = ["1lp3", "6j6j", "1mbo", "1hew", "1igt"]

    rendered = []
    for idx, pdb_id in enumerate(candidate_ids):
        cif = locate_cif(pdb_id, run_dir)
        if cif is None:
            continue
        print(f"\n[batch] CANDIDATE ── {pdb_id}")
        cmd.reinitialize()
        cmd.load(str(cif), pdb_id)
        cmd.viewport(800, 600)
        apply_scene(scene_id=scene_id)
        cmd.png(str(run_dir / f"{pdb_id}_applied.png"), width=800, height=600, ray=1)
        print(f"  ✓ {pdb_id}_applied.png")
        rendered.append(pdb_id)

    # Patch source.json with final PDB list and all RCSB URLs
    _source_meta["PDB_codes"] = [ref] + rendered
    for pid in rendered:
        _source_meta["rcsb_urls"][pid.upper()] = rcsb_entry_url(pid)
    source_path.write_text(json.dumps(_source_meta, indent=2))

    cmd.quit()

    # ── Phase C: slides ───────────────────────────────────────────────────
    # Write run-specific visual_system_state.json so Vis plot slides reflect
    # the actual scene rather than the static test-data fallback.
    state = _build_visual_state(ctrl, scene_id)
    (run_dir / "visual_system_state.json").write_text(json.dumps(state, indent=2))
    print("  [state]  visual_system_state.json written")

    print("\n[batch] Generating slides …")
    Vis.build_deck(molecules=[ref] + rendered, output_dir=run_dir)

    slides_out = run_dir / "slides.html"
    latest = RANDOM_DIR / "latest.html"
    if slides_out.exists():
        shutil.copy2(slides_out, latest)
        print(f"  [copy]   latest.html ← {run_tag}/slides.html")
        if _ui:
            # Write a done-marker so the UI can detect completion via HEAD request
            (RANDOM_DIR / f"{run_tag}.done").write_text(run_tag)
    else:
        print("[batch] WARN: slides.html not found, skipping copy")
    print("[batch] Done.")


if __name__ == "__main__":
    # Usage: python batch.py <ref_pdb_id>
    # ref_pdb_id — the PDB code enzyme.py was run on (e.g. 9ax6)
    if len(sys.argv) != 2:
        print("Usage: python batch.py <ref_pdb_id>")
        sys.exit(1)
    main(sys.argv[1].lower())
